Fixes #21 (#22)
ValueError: ("the use of non-builtin globals isn't supported")

Due to differences between `venv` and `virtualenv`, recommended is
latter.

Fully dropped support for Python 2.7.
Added explicit requirement for virtualenv.